name: CI/CD Deploy Private Repo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: git
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Cria pasta se não existir
            mkdir -p /var/www/snakegame
            cd /var/www/snakegame

            # Adiciona GitHub ao known_hosts
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts

            # Clona ou atualiza o repositório
            if [ ! -d ".git" ]; then
              echo "Pasta não existe, clonando repo..."
              git clone git@github.com:Corvaum/snakegame.git .
            else
              echo "Repo já existe, atualizando..."
              git pull origin main
            fi
