name: CI/CD Deploy Private Repo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Configura SSH
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      # Clonar ou atualizar o repositório
      - name: Git Clone / Pull
        run: |
          if [ ! -d "/var/www/mercadodeleads/.git" ]; then
            echo "Pasta não existe ou não é um repo git. Clonando..."
            git clone git@github.com:Corvaum/mercadodeleads.git /var/www/mercadodeleads
          else
            echo "Repo já existe. Atualizando..."
            cd /var/www/mercadodeleads
            git pull origin main
          fi

      # php scripts
      - name: php scripts
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # cd /var/www/mercadodeleads
            # composer install --no-dev
            # php artisan migrate --force
            # php artisan optimize
